import Head from 'next/head'
// import styles from '../styles/Home.module.css';
import Home from './Home';


export default function Index() {
  return (
    <div>
      <Head>
        <title>Pod</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
      </Head>

      {/* <main className={styles.main}> */}
      {/* <Navbar /> */}
      <Home />
      {/* </main>  className={styles.container}*/}


    </div>
  )
}
